services:
  mysql:
    image: mysql:8.0.32
    hostname: mysql
    container_name: honeypot_mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: cowrie
      MYSQL_USER: cowrie
      MYSQL_PASSWORD: 
