services:
  mysql:
    image: mysql:8.0.32
    hostname: mysql
    container_name: honeypot_mysql
    ports:
      - {{ mysql_port }}:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: {{ mysql_root_password }}
      MYSQL_DATABASE: {{ mysql_database }}
      MYSQL_USER: {{ mysql_username }}
      MYSQL_PASSWORD: {{ mysql_password }}
